// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlsuMzF8XjNDL4hTB6hRRyV3MwXhJ-BXA',
    appId: '1:747774290470:web:75ced5ca73e27a957494e7',
    messagingSenderId: '747774290470',
    projectId: 'auth-modul-61bc8',
    authDomain: 'auth-modul-61bc8.firebaseapp.com',
    storageBucket: 'auth-modul-61bc8.firebasestorage.app',
    measurementId: 'G-WYFRLKCVPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWaPXZVvR8VWYcW1IXhAhxMB1nIe_U0OA',
    appId: '1:747774290470:android:02de758349fb6b187494e7',
    messagingSenderId: '747774290470',
    projectId: 'auth-modul-61bc8',
    storageBucket: 'auth-modul-61bc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRVRjQHwJxS9SJQap55t6UqEphGTUlzXg',
    appId: '1:747774290470:ios:b45910ad1b39ab747494e7',
    messagingSenderId: '747774290470',
    projectId: 'auth-modul-61bc8',
    storageBucket: 'auth-modul-61bc8.firebasestorage.app',
    iosBundleId: 'com.example.ppbAuthModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRVRjQHwJxS9SJQap55t6UqEphGTUlzXg',
    appId: '1:747774290470:ios:b45910ad1b39ab747494e7',
    messagingSenderId: '747774290470',
    projectId: 'auth-modul-61bc8',
    storageBucket: 'auth-modul-61bc8.firebasestorage.app',
    iosBundleId: 'com.example.ppbAuthModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlsuMzF8XjNDL4hTB6hRRyV3MwXhJ-BXA',
    appId: '1:747774290470:web:e9efafdbb680b14f7494e7',
    messagingSenderId: '747774290470',
    projectId: 'auth-modul-61bc8',
    authDomain: 'auth-modul-61bc8.firebaseapp.com',
    storageBucket: 'auth-modul-61bc8.firebasestorage.app',
    measurementId: 'G-JY9Q00RLCX',
  );
}
